name: Playwright Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-checks:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Static Check
        run: npm run static-checks

  test-run:
    needs: static-checks
    if: success()
    timeout-minutes: 90
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npm run runAll
        env:
          HOME: /root
          TOKEN: ${{ secrets.TOKEN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
